site_name: Blog
site_url: https://ivansaul.github.io/docs
repo_url: https://github.com/ivansaul/docs
repo_name: ivansaul/docs
edit_uri: edit/master/docs/
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

    - content.action.view
    - content.action.edit

  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

nav:
  - SWIFT:
      - Getting Started:
          - swift/getting-started/extensions-in-swift.md

  - SWIFTUI:
      - Getting Started:
          - swiftui/getting-started/creating-shapes-in-swiftui.md

markdown_extensions:
  - attr_list
  - md_in_html

  - admonition
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox:
      zoomable: false
      draggable: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: ivansaul/docs
      branch: master

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/squidfunk

extra_css:
  - stylesheets/extras.css
